services:
  rails:
    container_name: rails-example
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/app
    env_file:
      - .env
    ports:
      - ${RAILS_PORT}:3000
    tty: true
    stdin_open: true
    depends_on:
      - mysql
  mysql:
    container_name: rails-example-db
    image: mysql:8.4.3
    volumes:
      - db-data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: ${MYSQL_DB}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      TZ: "Asia/Tokyo"
    ports:
      - ${MYSQL_PORT}:3306

volumes:
  db-data:
